<?php

/**
 * The class holding all the logic for the 'Microsoft Entra ID' settings page used to configure the plugin.
 *
 * Partially generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class AADSSO_Settings_Page {

	/**
	 * The stored settings (with defaults, if the setting isn't stored).
	 */
	private $settings;

	/**
	 * The option page's hook_suffix returned from add_options_page
	 */
	private $options_page_id;

	public function __construct() {

		// Ensure jQuery is loaded.
		add_action( 'admin_enqueue_scripts', array( $this, 'maybe_include_jquery' ) );

		// Add the 'Microsoft Entra ID' options page.
		add_action( 'admin_menu', array( $this, 'add_options_page' ) );

		// Register the settings.
		add_action( 'admin_init', array( $this, 'register_settings' ) );

		// Reset settings if requested to.
		add_action( 'admin_init', array( $this, 'maybe_reset_settings' ) );

		// Migrate settings if requested to.
		add_action( 'admin_init', array( $this, 'maybe_migrate_settings' ) );

		// If settings were reset, show confirmation.
		add_action( 'all_admin_notices', array( $this, 'notify_if_reset_successful' ) );

		// If settings were migrated, show confirmation
		add_action( 'all_admin_notices', array( $this, 'notify_json_migrate_status' ) );

		// Generate and download locally managed certificate credentials.
		add_action(
			'admin_post_aadsso_generate_certificate',
			array( $this, 'generate_self_signed_certificate' )
		);
		// The settings-page route avoids hosts that do not dispatch custom admin-post actions.
		add_action(
			'admin_init',
			array( $this, 'maybe_generate_self_signed_certificate' )
		);
		add_action(
			'admin_post_aadsso_download_certificate',
			array( $this, 'download_public_certificate' )
		);
		add_action(
			'admin_init',
			array( $this, 'maybe_download_public_certificate' )
		);
		add_action( 'all_admin_notices', array( $this, 'notify_certificate_action_status' ) );

		// Remove query arguments from the REQUEST_URI (leaves $_GET untouched).  Resolves issue #58
		$_SERVER['REQUEST_URI'] = remove_query_arg( 'aadsso_reset', $_SERVER['REQUEST_URI'] );
		$_SERVER['REQUEST_URI'] = remove_query_arg( 'aadsso_migrate_from_json_status', $_SERVER['REQUEST_URI'] );

		// Load stored configuration values, with defaults if there's nothing set.
		$default_settings = AADSSO_Settings::get_defaults();
		$this->settings = get_option( 'aadsso_settings', $default_settings );
		foreach ( $default_settings as $key => $default_value ) {
			if ( ! isset( $this->settings[ $key ] ) ) {
				$this->settings[ $key ] = $default_value;
			}
		}
	}

	/**
	 * Clears settings if $_GET['aadsso_nonce'] is set and if the nonce is valid.
	 */
	public function maybe_reset_settings()
	{
		$should_reset_settings = isset( $_GET['aadsso_nonce'] )
		                          && wp_verify_nonce( $_GET['aadsso_nonce'], 'aadsso_reset_settings' );
		if ( $should_reset_settings ) {
			delete_option( 'aadsso_settings' );
			delete_option( 'aadsso_settings_backup' );
			wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_reset=success' ) );
		}
	}

	/**
	 * Migrates old settings (Settings.json) to the database and attempts to delete the old settings file.
	 */
	public function maybe_migrate_settings() {
		/**
		 * Settings should only be migrated if
		 * - The request came from a nonced link
		 * - The nonce action is 'aadsso_migrate_settings'
		 * - There is a legacy settings path defined
		 * - There is a file at that legacy settings path
		 */
		$should_migrate_settings = isset( $_GET['aadsso_nonce'] )
			&& wp_verify_nonce( $_GET['aadsso_nonce'], 'aadsso_migrate_from_json' )
			&& defined( 'AADSSO_SETTINGS_PATH' )
			&& file_exists( AADSSO_SETTINGS_PATH );

		if ( $should_migrate_settings ) {

			$legacy_settings = json_decode( file_get_contents( AADSSO_SETTINGS_PATH ), true );

			if ( null === $legacy_settings ) {
				wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=invalid_json') );
			}

			// If aad_group_to_wp_role_map is set in the legacy settings, build the inverted role_map array,
			// which is what is ultimately saved in the database.
			if ( isset( $legacy_settings['aad_group_to_wp_role_map'] ) ) {
				$legacy_settings['role_map'] = array();
				foreach ($aad_group_to_wp_role_map as $group_id => $role_slug ) {
					if ( ! isset( $legacy_settings['role_map'][$role_slug] ) ) {
						$legacy_settings['role_map'][$role_slug] = $group_id;
					} else {
						$legacy_settings['role_map'][$role_slug] .= ',' . $group_id;
					}
				}
			}

			$sanitized_settings = $this->sanitize_settings( $legacy_settings );

			update_option( 'aadsso_settings', $sanitized_settings );

			if ( is_writable( AADSSO_SETTINGS_PATH ) && is_writable( dirname( AADSSO_SETTINGS_PATH ) ) && unlink( AADSSO_SETTINGS_PATH ) ) {
				wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=success' ) );
			} else {
				wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=manual' ) );
			}
		}
	}

	/**
	 * Shows messages about the state of the migration operation
	 */
	public function notify_json_migrate_status() {
		if( isset( $_GET['aadsso_migrate_from_json_status'] ) ) {
			if( 'success' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-success"><p>'
					. __( 'Legacy settings have been migrated and the old configuration file has been deleted.', 'aad-sso-wordpress' )
					. __('To finish migration, unset <code>AADSSO_SETTINGS_PATH</code> from <code>wp-config.php</code>. ', 'aad-sso-wordpress')
					.'</p></div>';
			} elseif ( 'manual' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-warning"><p>'
					. esc_html__( 'Legacy settings have been migrated successfully. ', 'aad-sso-wordpress' )
					. sprintf( __('To finish migration, delete the file at the path <code>%s</code>. ', 'aad-sso-wordpress'), AADSSO_SETTINGS_PATH )
					. sprintf( __('Then, unset <code>AADSSO_SETTINGS_PATH</code> from <code>wp-config.php</code>. ', 'aad-sso-wordpress') )
					.'</p></div>';
			} elseif( 'invalid_json' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-error"><p>'
					. sprintf( __('Legacy settings could not be migrated from <code>%s</code>. ', 'aad-sso-wordpress'), AADSSO_SETTINGS_PATH )
					. esc_html( 'File could not be parsed as JSON. ', 'aad-sso-wordpress' )
					. esc_html( 'Delete the file, or check its syntax.', 'aad-sso-wordpress' )
					.'</p></div>';
			}
		}
	}

	/**
	 * Notifies user if settings reset was successful.
	 */
	public function notify_if_reset_successful()
	{
		if ( isset( $_GET['aadsso_reset'] ) && 'success' === $_GET['aadsso_reset'] ) {
			echo '<div id="message" class="notice notice-warning"><p>'
				. __( 'Single Sign-on with Microsoft Entra ID settings have been reset to default.',
					'aad-sso-wordpress' )
				.'</p></div>';
		}
	}

	/**
	 * Handles certificate generation directly from the plugin settings page.
	 */
	public function maybe_generate_self_signed_certificate() {
		$is_generation_request = isset( $_GET['page'], $_GET['aadsso_action'] )
			&& 'aadsso_settings' === $_GET['page']
			&& 'generate_certificate' === $_GET['aadsso_action']
			&& isset( $_SERVER['REQUEST_METHOD'] )
			&& 'POST' === strtoupper( $_SERVER['REQUEST_METHOD'] );
		if ( $is_generation_request ) {
			$this->generate_self_signed_certificate();
		}
	}

	/**
	 * Generates and stores a self-signed certificate credential.
	 */
	public function generate_self_signed_certificate() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You are not allowed to manage these settings.', 'aad-sso-wordpress' ) );
		}
		check_admin_referer( 'aadsso_generate_certificate', 'aadsso_generate_nonce' );

		$settings = get_option( 'aadsso_settings', AADSSO_Settings::get_defaults() );
		$has_existing_certificate = ! empty( $settings['client_certificate'] )
			|| ! empty( $settings['client_private_key_encrypted'] );
		$replace_confirmed = isset( $_POST['aadsso_replace_certificate'] )
			&& '1' === $_POST['aadsso_replace_certificate'];

		if ( $has_existing_certificate && ! $replace_confirmed ) {
			$this->redirect_after_certificate_action( 'replace_not_confirmed' );
		}

		$valid_days = isset( $_POST['aadsso_certificate_valid_days'] )
			? absint( $_POST['aadsso_certificate_valid_days'] ) : 730;
		$valid_days = max( 30, min( 3650, $valid_days ) );
		$site_host = parse_url( home_url(), PHP_URL_HOST );
		$common_name = ! empty( $site_host ) ? $site_host : get_bloginfo( 'name' );

		try {
			$credentials = AADSSO_CredentialHelper::generate_self_signed_credentials(
				$common_name,
				$valid_days,
				3072
			);
			$settings['client_certificate'] = $credentials['certificate'];
			$settings['client_private_key_encrypted'] =
				AADSSO_CredentialHelper::encrypt_private_key( $credentials['private_key'] );
			$settings['client_auth_method'] = 'certificate';

			/*
			 * register_setting() attaches sanitize_settings() to every update_option() call.
			 * Generated credentials are already validated and the private key is already
			 * encrypted, so temporarily bypass the form sanitizer that expects a plaintext
			 * private key alongside a pasted public certificate.
			 */
			remove_filter(
				'sanitize_option_aadsso_settings',
				array( $this, 'sanitize_settings' )
			);
			try {
				update_option( 'aadsso_settings', $settings );
			} finally {
				add_filter(
					'sanitize_option_aadsso_settings',
					array( $this, 'sanitize_settings' )
				);
			}

			$saved_settings = get_option( 'aadsso_settings', array() );
			if ( empty( $saved_settings['client_certificate'] )
				|| empty( $saved_settings['client_private_key_encrypted'] )
				|| 'certificate' !== $saved_settings['client_auth_method']
			) {
				throw new RuntimeException(
					'WordPress did not persist the generated certificate credentials.'
				);
			}
		} catch ( Exception $exception ) {
			$this->handle_certificate_generation_failure( $exception );
		} catch ( Error $error ) {
			// PHP 7+ OpenSSL calls can throw Error/ValueError instead of returning false.
			$this->handle_certificate_generation_failure( $error );
		}

		$this->redirect_after_certificate_action( 'generated' );
	}

	/**
	 * Records a safe diagnostic for the administrator and returns to the settings page.
	 *
	 * @param Exception|Error $error Certificate generation failure.
	 */
	private function handle_certificate_generation_failure( $error ) {
		$message = is_object( $error ) && method_exists( $error, 'getMessage' )
			? $error->getMessage()
			: __( 'Unknown certificate generation error.', 'aad-sso-wordpress' );
		AADSSO::debug_log( 'Unable to generate self-signed certificate: ' . $message );
		set_transient(
			'aadsso_certificate_generation_error_' . get_current_user_id(),
			sanitize_text_field( $message ),
			120
		);
		$this->redirect_after_certificate_action( 'generation_failed' );
	}

	/**
	 * Handles the certificate download directly from the plugin settings page.
	 */
	public function maybe_download_public_certificate() {
		$is_download_request = isset( $_GET['page'], $_GET['aadsso_action'] )
			&& 'aadsso_settings' === $_GET['page']
			&& 'download_certificate' === $_GET['aadsso_action']
			&& ( ! isset( $_SERVER['REQUEST_METHOD'] )
				|| 'GET' === strtoupper( $_SERVER['REQUEST_METHOD'] ) );
		if ( $is_download_request ) {
			$this->download_public_certificate();
		}
	}

	/**
	 * Downloads the stored public certificate. The private key is never included.
	 */
	public function download_public_certificate() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You are not allowed to manage these settings.', 'aad-sso-wordpress' ) );
		}
		check_admin_referer( 'aadsso_download_certificate' );

		$settings = get_option( 'aadsso_settings', array() );
		if ( empty( $settings['client_certificate'] ) ) {
			wp_die( esc_html__( 'No public certificate is stored.', 'aad-sso-wordpress' ) );
		}

		$site_host = parse_url( home_url(), PHP_URL_HOST );
		$file_name = sanitize_file_name(
			( ! empty( $site_host ) ? $site_host : 'wordpress' ) . '-entra-sso.cer'
		);

		nocache_headers();
		header( 'Content-Type: application/pkix-cert' );
		header( 'Content-Disposition: attachment; filename="' . $file_name . '"' );
		header( 'Content-Length: ' . strlen( $settings['client_certificate'] ) );
		echo $settings['client_certificate'];
		exit;
	}

	/**
	 * Returns a nonce-protected URL for downloading the stored public certificate.
	 */
	private function get_certificate_download_url() {
		return wp_nonce_url(
			admin_url(
				'options-general.php?page=aadsso_settings&aadsso_action=download_certificate'
			),
			'aadsso_download_certificate'
		);
	}

	/**
	 * Shows the result of certificate generation.
	 */
	public function notify_certificate_action_status() {
		if ( ! isset( $_GET['aadsso_certificate_status'] ) ) {
			return;
		}

		$status = sanitize_key( $_GET['aadsso_certificate_status'] );
		$messages = array(
			'generated' => array(
				'success',
				__( 'A self-signed certificate was generated and Certificate authentication was selected. Download the public certificate and upload it to the Entra app registration before the next sign-in.', 'aad-sso-wordpress' ),
			),
			'replace_not_confirmed' => array(
				'warning',
				__( 'The existing certificate was not replaced because replacement was not confirmed.', 'aad-sso-wordpress' ),
			),
			'generation_failed' => array(
				'error',
				__( 'The server could not generate the certificate. Confirm that the PHP OpenSSL extension and its configuration are available.', 'aad-sso-wordpress' ),
			),
		);

		if ( isset( $messages[ $status ] ) ) {
			$message = $messages[ $status ][1];
			if ( 'generation_failed' === $status ) {
				$error_key = 'aadsso_certificate_generation_error_' . get_current_user_id();
				$error_detail = get_transient( $error_key );
				delete_transient( $error_key );
				if ( $error_detail ) {
					$message .= ' ' . sprintf(
						__( 'Server detail: %s', 'aad-sso-wordpress' ),
						$error_detail
					);
				}
			}
			echo '<div class="notice notice-' . esc_attr( $messages[ $status ][0] )
				. ' is-dismissible"><p>' . esc_html( $message ) . '</p>';
			if ( 'generated' === $status ) {
				echo '<p><a class="button button-primary" href="'
					. esc_url( $this->get_certificate_download_url() ) . '">'
					. esc_html__( 'Download public certificate (.cer)', 'aad-sso-wordpress' )
					. '</a></p>';
			}
			echo '</div>';
		}
	}

	/**
	 * Redirects to the settings page after a certificate action.
	 *
	 * @param string $status Fixed action status.
	 */
	private function redirect_after_certificate_action( $status ) {
		wp_safe_redirect(
			add_query_arg(
				'aadsso_certificate_status',
				$status,
				admin_url( 'options-general.php?page=aadsso_settings' )
			)
		);
		exit;
	}

	/**
	 * Adds the 'Microsoft Entra ID' options page.
	 */
	public function add_options_page() {
		$this->options_page_id = add_options_page(
			__( 'Microsoft Entra ID Settings', 'aad-sso-wordpress' ), // page_title
			'Microsoft Entra ID', // menu_title
			'manage_options', // capability
			'aadsso_settings', // menu_slug
			array( $this, 'render_admin_page' ) // function
		);
	}

	/**
	 * Renders the 'Microsoft Entra ID' settings page.
	 */
	public function render_admin_page() {
		require_once( 'view/settings.php' );
	}

	/**
	 * Registers settings, sections and fields.
	 */
	public function register_settings() {

		register_setting(
			'aadsso_settings', // option_group
			'aadsso_settings', // option_name
			array( $this, 'sanitize_settings' ) // sanitize_callback
		);

		add_settings_section(
			'aadsso_settings_general', // id
			__( 'General', 'aad-sso-wordpress' ), // title
			array( $this, 'settings_general_info' ), // callback
			'aadsso_settings_page' // page
		);

		add_settings_section(
			'aadsso_settings_advanced', // id
			__( 'Advanced', 'aad-sso-wordpress' ), // title
			array( $this, 'settings_advanced_info' ), // callback
			'aadsso_settings_page' // page
		);

		add_settings_field(
			'org_display_name', // id
			__( 'Display name', 'aad-sso-wordpress' ), // title
			array( $this, 'org_display_name_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'org_domain_hint', // id
			__( 'Domain hint', 'aad-sso-wordpress' ), // title
			array( $this, 'org_domain_hint_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_id', // id
			__( 'Client ID', 'aad-sso-wordpress' ), // title
			array( $this, 'client_id_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_auth_method', // id
			__( 'Client authentication', 'aad-sso-wordpress' ), // title
			array( $this, 'client_auth_method_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_secret', // id
			__( 'Client secret', 'aad-sso-wordpress' ), // title
			array( $this, 'client_secret_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_certificate', // id
			__( 'Client certificate', 'aad-sso-wordpress' ), // title
			array( $this, 'client_certificate_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_private_key', // id
			__( 'Certificate private key', 'aad-sso-wordpress' ), // title
			array( $this, 'client_private_key_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'redirect_uri', // id
			__( 'Redirect URL', 'aad-sso-wordpress' ), // title
			array( $this, 'redirect_uri_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'logout_redirect_uri', // id
			__( 'Logout redirect URL', 'aad-sso-wordpress' ), // title
			array( $this, 'logout_redirect_uri_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);
		
		add_settings_field(
			'enable_full_logout', // id
			__( 'Enable full logout', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_full_logout_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'prompt', // id
			__( 'Login prompt behavior', 'aad-sso-wordpress' ), // title
			array( $this, 'prompt_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'field_to_match_to_upn', // id
			__( 'Field to match to UPN', 'aad-sso-wordpress' ), // title
			array( $this, 'field_to_match_to_upn_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'match_on_upn_alias', // id
			__( 'Match on alias of the UPN', 'aad-sso-wordpress' ), // title
			array( $this, 'match_on_upn_alias_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_auto_provisioning', // id
			__( 'Enable auto-provisioning', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_auto_provisioning_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_profile_photo_sync', // id
			__( 'Enable Microsoft Graph profile photo sync', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_profile_photo_sync_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_auto_forward_to_aad', // id
			__( 'Enable auto-forward to Microsoft Entra ID', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_auto_forward_to_aad_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_aad_group_to_wp_role', // id
			__( 'Enable Microsoft Entra ID group to WordPress role association', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_aad_group_to_wp_role_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'default_wp_role', // id
			__( 'Default WordPress role if not in Microsoft Entra ID group', 'aad-sso-wordpress' ), // title
			array( $this, 'default_wp_role_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'role_map', // id
			__( 'WordPress role to Microsoft Entra ID group map', 'aad-sso-wordpress' ), // title
			array( $this, 'role_map_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'openid_configuration_endpoint', // id
			__( 'OpenID Connect configuration endpoint', 'aad-sso-wordpress' ), // title
			array( $this, 'openid_configuration_endpoint_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_advanced' // section
		);
	}

	/**
	 * Gets the array of roles determined by other plugins to be "editable".
	 */
	function get_editable_roles() {

		global $wp_roles;

		$all_roles = $wp_roles->roles;
		$editable_roles = apply_filters( 'editable_roles', $all_roles );

		return $editable_roles;
	}

	/**
	 * Cleans and validates form information before saving.
	 *
	 * @param array $input key-value information to be cleaned before saving.
	 *
	 * @return array The sanitized and valid data to be stored.
	 */
	public function sanitize_settings( $input ) {

		$sanitary_values = array();

		$text_fields = array(
			'org_display_name',
			'org_domain_hint',
			'client_id',
			'redirect_uri',
			'logout_redirect_uri',
			'openid_configuration_endpoint',
		);

		foreach ($text_fields as $text_field) {
			if ( isset( $input[ $text_field ] ) ) {
				$sanitary_values[ $text_field ] = sanitize_text_field( $input[ $text_field ] );
			}
		}

		$stored_auth_method = isset( $this->settings['client_auth_method'] )
			? $this->settings['client_auth_method'] : 'secret';
		$sanitary_values['client_auth_method'] =
			isset( $input['client_auth_method'] )
			&& in_array( $input['client_auth_method'], array( 'secret', 'certificate' ), true )
				? $input['client_auth_method'] : 'secret';

		// Client secrets and private keys are write-only fields. Blank input preserves the stored value.
		$sanitary_values['client_secret'] = isset( $this->settings['client_secret'] )
			? $this->settings['client_secret'] : '';
		if ( ! empty( $input['remove_client_secret'] ) ) {
			$sanitary_values['client_secret'] = '';
		} elseif ( isset( $input['client_secret'] ) && '' !== trim( $input['client_secret'] ) ) {
			$sanitary_values['client_secret'] = sanitize_text_field( $input['client_secret'] );
		}

		$sanitary_values['client_certificate'] = isset( $this->settings['client_certificate'] )
			? $this->settings['client_certificate'] : '';
		$sanitary_values['client_private_key_encrypted'] =
			isset( $this->settings['client_private_key_encrypted'] )
				? $this->settings['client_private_key_encrypted'] : '';

		if ( ! empty( $input['remove_certificate_credentials'] ) ) {
			$sanitary_values['client_certificate'] = '';
			$sanitary_values['client_private_key_encrypted'] = '';
			if ( 'certificate' === $sanitary_values['client_auth_method'] ) {
				$sanitary_values['client_auth_method'] = 'secret';
			}
		} else {
			$certificate_input = isset( $input['client_certificate'] )
				? trim( wp_unslash( $input['client_certificate'] ) ) : '';
			$private_key_input = isset( $input['client_private_key'] )
				? trim( wp_unslash( $input['client_private_key'] ) ) : '';
			$private_key_passphrase = isset( $input['client_private_key_passphrase'] )
				? wp_unslash( $input['client_private_key_passphrase'] ) : '';
			$stored_certificate = isset( $this->settings['client_certificate'] )
				? trim( $this->settings['client_certificate'] ) : '';
			$comparable_certificate_input = str_replace(
				array( "\r\n", "\r" ),
				"\n",
				$certificate_input
			);
			$comparable_stored_certificate = str_replace(
				array( "\r\n", "\r" ),
				"\n",
				$stored_certificate
			);
			$certificate_is_unchanged = '' !== $certificate_input
				&& '' === $private_key_input
				&& $comparable_certificate_input === $comparable_stored_certificate;

			if ( ! $certificate_is_unchanged
				&& ( '' !== $certificate_input || '' !== $private_key_input )
			) {
				try {
					if ( '' === $certificate_input || '' === $private_key_input ) {
						throw new InvalidArgumentException(
							'Provide both the public certificate and its matching private key.'
						);
					}

					$credentials = AADSSO_CredentialHelper::validate_and_normalize_credentials(
						$certificate_input,
						$private_key_input,
						$private_key_passphrase
					);
					$sanitary_values['client_certificate'] = $credentials['certificate'];
					$sanitary_values['client_private_key_encrypted'] =
						AADSSO_CredentialHelper::encrypt_private_key( $credentials['private_key'] );
					add_settings_error(
						'aadsso_settings',
						'aadsso_certificate_saved',
						__( 'The certificate credentials were validated and the private key was encrypted.', 'aad-sso-wordpress' ),
						'updated'
					);
				} catch ( Exception $exception ) {
					$sanitary_values['client_auth_method'] = $stored_auth_method;
					add_settings_error(
						'aadsso_settings',
						'aadsso_invalid_certificate',
						sprintf(
							__( 'Certificate credentials were not saved: %s', 'aad-sso-wordpress' ),
							$exception->getMessage()
						),
						'error'
					);
				}
			}
		}

		if ( 'certificate' === $sanitary_values['client_auth_method']
			&& ( empty( $sanitary_values['client_certificate'] )
				|| empty( $sanitary_values['client_private_key_encrypted'] ) )
		) {
			$sanitary_values['client_auth_method'] =
				'certificate' === $stored_auth_method ? 'secret' : $stored_auth_method;
			add_settings_error(
				'aadsso_settings',
				'aadsso_missing_certificate',
				__( 'Certificate authentication cannot be enabled until a certificate and private key are saved.', 'aad-sso-wordpress' ),
				'error'
			);
		}

		// Default prompt is empty (omit parameter).
		$sanitary_values['prompt'] = '';
		if ( isset( $input['prompt'] )
			&& in_array( $input['prompt'], array( 'login', 'select_account' ), true )
		) {
			$sanitary_values['prompt'] = $input['prompt'];
		}

		// Default field_to_match_to_upn is 'email'
		$sanitary_values['field_to_match_to_upn'] = 'email';
		if ( isset( $input['field_to_match_to_upn'] )
		      && in_array( $input['field_to_match_to_upn'], array( 'email', 'login' ) )
		) {
			$sanitary_values['field_to_match_to_upn'] = $input['field_to_match_to_upn'];
		}

		// Default role for user that is not member of any Microsoft Entra ID group is null, which denies access.
		$sanitary_values['default_wp_role'] = null;
		if ( isset( $input['default_wp_role'] ) ) {
			$sanitary_values['default_wp_role'] = sanitize_text_field( $input['default_wp_role'] );
		}

		// Booleans: when key == value, this is considered true, otherwise false.
		$boolean_settings = array(
			'enable_auto_provisioning',
			'enable_profile_photo_sync',
			'enable_auto_forward_to_aad',
			'enable_aad_group_to_wp_role',
			'match_on_upn_alias',
			'enable_full_logout',
		);
		foreach ( $boolean_settings as $boolean_setting )
		{
			if( isset( $input[ $boolean_setting ] ) ) {
				$sanitary_values[ $boolean_setting ] = ( $boolean_setting == $input[ $boolean_setting ] );
			} else {
				$sanitary_values[ $boolean_setting ] = false;
			}
		}

		/*
		 * Many of the roles in WordPress will not have Microsoft Entra ID groups associated with them.
		 * Go over all roles, removing the mapping for empty ones.
		 */
		if ( isset( $input['role_map'] ) ) {
			foreach( $input['role_map'] as $role_slug => $group_object_id ) {
				if( empty( $group_object_id ) ) {
					unset( $input['role_map'][ $role_slug ] );
				}
			}
			$sanitary_values['role_map'] = $input['role_map'];
		}

		// If the OpenID Connect configuration endpoint is changed, clear the cached values.
		$stored_oidc_config_endpoint = isset( $this->settings['openid_configuration_endpoint'] )
			? $this->settings['openid_configuration_endpoint'] : null;
		if ( $stored_oidc_config_endpoint !== $sanitary_values['openid_configuration_endpoint'] ) {
			delete_transient( 'aadsso_openid_configuration' );
			AADSSO::debug_log('Setting \'openid_configuration_endpoint\' changed, cleared cached OpenID Connect values.');
		}

		return $sanitary_values;
	}

	/**
	 * Renders details for the General settings section.
	 */
	public function settings_general_info() { }

	/**
	 * Renders details for the Advanced settings section.
	 */
	public function settings_advanced_info() { }

	/**
	 * Renders the `role_map` picker control.
	 */
	function role_map_callback() {
		printf( '<p>%s</p>',
			__( 'Map WordPress roles to Microsoft Entra ID groups.', 'aad-sso-wordpress' )
		);
		echo '<table>';
		printf(
			'<thead><tr><th>%s</th><th>%s</th></tr></thead>',
			__( 'WordPress Role', 'aad-sso-wordpress' ),
			__( 'Microsoft Entra ID Group Object ID', 'aad-sso-wordpress' )
		);
		echo '<tbody>';
		foreach( $this->get_editable_roles( ) as $role_slug => $role ) {
			echo '<tr>';
				echo '<td>' . htmlentities( $role['name'] ) . '</td>';
				echo '<td>';
					printf(
						'<input type="text" class="regular-text" name="aadsso_settings[role_map][%1$s]" '
						 . 'id="role_map_%1$s" value="%2$s" />',
						$role_slug,
						isset( $this->settings['role_map'][ $role_slug ] )
							? esc_attr( $this->settings['role_map'][ $role_slug ] )
							: ''
					);
				echo '</td>';
			echo '</tr>';
		}
		echo '</tbody>';
		echo '</table>';
	}

	/**
	 * Renders the `org_display_name` form control.
	 */
	public function org_display_name_callback()  {
		$this->render_text_field( 'org_display_name' );
		printf(
			'<p class="description">%s</p>',
			__( 'Display Name will be shown on the WordPress login screen.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `org_domain_hint` form control.
	 */
	public function org_domain_hint_callback()  {
		$this->render_text_field( 'org_domain_hint' );
		printf(
			'<p class="description">%s</p>',
			__( 'Provides a hint to Microsoft Entra ID about the domain or tenant they will be logging in to. If '
			     . 'the domain is federated, the user will be automatically redirected to federation '
			     . 'endpoint.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `client_id` form control
	 */
	public function client_id_callback() {
		$this->render_text_field( 'client_id' );
		printf(
			'<p class="description">%s</p>',
			__( 'The client ID of the Microsoft Entra ID application representing this blog.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the client authentication method control.
	 */
	public function client_auth_method_callback() {
		$selected = isset( $this->settings['client_auth_method'] )
			? $this->settings['client_auth_method'] : 'secret';
		$options = array(
			'secret' => __( 'Client secret', 'aad-sso-wordpress' ),
			'certificate' => __( 'Certificate (private key JWT)', 'aad-sso-wordpress' ),
		);

		echo '<fieldset>';
		foreach ( $options as $value => $label ) {
			printf(
				'<label><input type="radio" name="aadsso_settings[client_auth_method]" value="%s"%s /> %s</label><br />',
				esc_attr( $value ),
				checked( $selected, $value, false ),
				esc_html( $label )
			);
		}
		echo '</fieldset>';
	}

	/**
	 * Renders the `client_secret` form control
	 **/
	public function client_secret_callback() {
		printf(
			'<input class="regular-text" type="password" autocomplete="new-password" '
			. 'name="aadsso_settings[client_secret]" id="client_secret" value="" />'
		);
		if ( ! empty( $this->settings['client_secret'] ) ) {
			echo '<p><strong>' . esc_html__( 'A client secret is currently stored.', 'aad-sso-wordpress' ) . '</strong></p>';
			echo '<label><input type="checkbox" name="aadsso_settings[remove_client_secret]" value="1" /> '
				. esc_html__( 'Remove the stored client secret', 'aad-sso-wordpress' ) . '</label>';
		}
		printf(
			'<p class="description">%s</p>',
			__( 'Leave blank to keep the stored secret. Used only when Client secret authentication is selected.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the public certificate control and stored certificate details.
	 */
	public function client_certificate_callback() {
		$stored_certificate = ! empty( $this->settings['client_certificate'] )
			? $this->settings['client_certificate'] : '';
		echo '<textarea class="large-text code" rows="8" name="aadsso_settings[client_certificate]" '
			. 'id="client_certificate" autocomplete="off" placeholder="-----BEGIN CERTIFICATE-----">'
			. esc_textarea( $stored_certificate ) . '</textarea>';
		echo '<p class="description">'
			. esc_html__( 'The stored PEM X.509 public certificate. Replace it together with its matching private key when using manually supplied credentials.', 'aad-sso-wordpress' )
			. '</p>';

		if ( ! empty( $this->settings['client_certificate'] ) ) {
			try {
				$thumbprint = AADSSO_CredentialHelper::get_certificate_thumbprint(
					$this->settings['client_certificate']
				);
				$details = AADSSO_CredentialHelper::get_certificate_details(
					$this->settings['client_certificate']
				);
				echo '<p><strong>' . esc_html__( 'A certificate is currently stored.', 'aad-sso-wordpress' ) . '</strong><br />';
				echo esc_html__( 'SHA-256 thumbprint:', 'aad-sso-wordpress' ) . ' <code>'
					. esc_html( $thumbprint ) . '</code>';
				if ( is_array( $details ) && ! empty( $details['validTo_time_t'] ) ) {
					echo '<br />' . esc_html__( 'Expires:', 'aad-sso-wordpress' ) . ' '
						. esc_html( date_i18n( get_option( 'date_format' ), $details['validTo_time_t'] ) );
				}
				echo '</p>';
				$download_url = $this->get_certificate_download_url();
				echo '<p><a class="button" href="' . esc_url( $download_url ) . '">'
					. esc_html__( 'Download public certificate (.cer)', 'aad-sso-wordpress' )
					. '</a></p>';
				echo '<details><summary>'
					. esc_html__( 'View PEM public certificate', 'aad-sso-wordpress' )
					. '</summary><textarea class="large-text code" rows="8" readonly>'
					. esc_textarea( $this->settings['client_certificate'] )
					. '</textarea></details>';
			} catch ( Exception $exception ) {
				echo '<p class="description">'
					. esc_html__( 'The stored certificate could not be inspected.', 'aad-sso-wordpress' )
					. '</p>';
			}
		}

		echo '<hr /><p><strong>'
			. esc_html__( 'Generate a self-signed certificate', 'aad-sso-wordpress' )
			. '</strong></p>';
		echo '<p><label for="aadsso_certificate_valid_days">'
			. esc_html__( 'Validity period:', 'aad-sso-wordpress' )
			. '</label> <select id="aadsso_certificate_valid_days" '
			. 'name="aadsso_certificate_valid_days">'
			. '<option value="365">' . esc_html__( '1 year', 'aad-sso-wordpress' ) . '</option>'
			. '<option value="730" selected>' . esc_html__( '2 years', 'aad-sso-wordpress' ) . '</option>'
			. '<option value="1095">' . esc_html__( '3 years', 'aad-sso-wordpress' ) . '</option>'
			. '</select></p>';
		wp_nonce_field(
			'aadsso_generate_certificate',
			'aadsso_generate_nonce',
			false
		);
		if ( ! empty( $this->settings['client_certificate'] )
			|| ! empty( $this->settings['client_private_key_encrypted'] )
		) {
			echo '<p><label><input type="checkbox" name="aadsso_replace_certificate" value="1" /> '
				. esc_html__( 'I understand this replaces the stored certificate and may interrupt SSO until the new public certificate is uploaded to Entra.', 'aad-sso-wordpress' )
				. '</label></p>';
		}
		printf(
			'<button type="submit" class="button" formmethod="post" formaction="%1$s">%2$s</button>',
			esc_url(
				admin_url(
					'options-general.php?page=aadsso_settings&aadsso_action=generate_certificate'
				)
			),
			esc_html__( 'Generate self-signed certificate', 'aad-sso-wordpress' )
		);
		echo '<p class="description">'
			. esc_html__( 'Generates a 3072-bit RSA private key on this server. The private key is encrypted in the database and is never displayed; only the public certificate can be downloaded.', 'aad-sso-wordpress' )
			. '</p>';
	}

	/**
	 * Renders write-only private key controls.
	 */
	public function client_private_key_callback() {
		echo '<textarea class="large-text code" rows="8" name="aadsso_settings[client_private_key]" '
			. 'id="client_private_key" autocomplete="new-password" '
			. 'placeholder="-----BEGIN PRIVATE KEY-----"></textarea>';
		echo '<p><label for="client_private_key_passphrase">'
			. esc_html__( 'Private key passphrase (only needed while saving):', 'aad-sso-wordpress' )
			. '</label><br /><input class="regular-text" type="password" autocomplete="new-password" '
			. 'name="aadsso_settings[client_private_key_passphrase]" '
			. 'id="client_private_key_passphrase" value="" /></p>';
		echo '<p class="description">'
			. esc_html__( 'The passphrase is never stored. The private key is normalized, encrypted, and integrity-protected before database storage.', 'aad-sso-wordpress' )
			. '</p>';

		if ( ! empty( $this->settings['client_private_key_encrypted'] ) ) {
			echo '<p><strong>'
				. esc_html__( 'An encrypted private key is currently stored.', 'aad-sso-wordpress' )
				. '</strong></p>';
			echo '<label><input type="checkbox" name="aadsso_settings[remove_certificate_credentials]" value="1" /> '
				. esc_html__( 'Remove the stored certificate and private key', 'aad-sso-wordpress' )
				. '</label>';
		}
	}

	/**
	 * Renders the `redirect_uri` form control
	 **/
	public function redirect_uri_callback() {
		$this->render_text_field( 'redirect_uri' );
		printf(
			' <a href="#" onclick="jQuery(\'#redirect_uri\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			wp_login_url(),
			__( 'Set default', 'aad-sso-wordpress' ),
			__( 'The URL where the user is redirected to after authenticating with Microsoft Entra ID. '
			  . 'This URL must be registered in Microsoft Entra ID as a valid redirect URL, and it must be a '
			  . 'page that invokes the "authenticate" filter. If you don\'t know what to set, leave '
			  . 'the default value (which is this blog\'s login page).', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `logout_redirect_uri` form control
	 **/
	public function logout_redirect_uri_callback() {
		$this->render_text_field( 'logout_redirect_uri' );
		printf(
			' <a href="#" onclick="jQuery(\'#logout_redirect_uri\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			wp_login_url(),
			__( 'Set default', 'aad-sso-wordpress'),
			__( 'The URL where the user is redirected to after signing out of Microsoft Entra ID. '
			  . 'This URL must be registered in Microsoft Entra ID as a valid redirect URL. (This does not affect '
			  . ' logging out of the blog, it is only used when logging out of Microsoft Entra ID.)', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `prompt` form control.
	 */
	public function prompt_callback() {
		$selected = isset( $this->settings['prompt'] ) ? $this->settings['prompt'] : '';
		$options = array(
			''               => __( '(Recommended) No prompt if already signed in', 'aad-sso-wordpress' ),
			'select_account' => __( 'Prompt to select account (<code>prompt=select_account</code>)', 'aad-sso-wordpress' ),
			'login'          => __( 'Prompt for fresh login (not recommended, <code>prompt=login</code>)', 'aad-sso-wordpress' ),
		);
		echo '<fieldset>';
		foreach ( $options as $value => $label ) {
			printf(
				'<label><input type="radio" name="aadsso_settings[prompt]" value="%s"%s /> %s</label><br />',
				esc_attr( $value ),
				checked( $selected, $value, false ),
				$label
			);
		}
		echo '</fieldset>';
	}

	/**
	 * Renders the `field_to_match_to_upn` form control.
	 */
	public function field_to_match_to_upn_callback() {
		$selected =
		 isset( $this->settings['field_to_match_to_upn'] )
			? $this->settings['field_to_match_to_upn']
			: '';
		?>
		<select name="aadsso_settings[field_to_match_to_upn]" id="field_to_match_to_upn">
			<option value="email"<?php echo $selected == 'email' ? ' selected="selected"' : ''; ?>>
				<?php echo __( 'Email Address', 'aad-sso-wordpress' ); ?>
			</option>
			<option value="login"<?php echo $selected == 'login' ? ' selected="selected"' : ''; ?>>
				<?php echo __( 'Login Name', 'aad-sso-wordpress' ); ?>
			</option>
		</select>
		<?php
		printf(
			'<p class="description">%s</p>',
			__( 'This specifies the WordPress user field which will be used to match to the Microsoft Entra ID user\'s '
			  . 'UserPrincipalName.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `match_on_upn_alias` checkbox control.
	 */
	public function match_on_upn_alias_callback() {
		$this->render_checkbox_field(
			'match_on_upn_alias',
			__( 'Match WordPress users based on the alias of their Microsoft Entra ID UserPrincipalName. For example, '
			  . 'Microsoft Entra ID username <code>bob@example.com</code> will match WordPress user <code>bob</code>.',
			    'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `default_wp_role` control.
	 */
	public function default_wp_role_callback() {

		// Default configuration should be most-benign
		if( ! isset( $this->settings['default_wp_role'] ) ) {
			$this->settings['default_wp_role'] = '';
		}

		echo '<select name="aadsso_settings[default_wp_role]" id="default_wp_role">';
		printf( '<option value="%s">%s</option>', '', '(None, deny access)' );
		foreach( $this->get_editable_roles() as $role_slug => $role ) {
			$selected = $this->settings['default_wp_role'] === $role_slug ? ' selected="selected"' : '';
			printf(
				'<option value="%s"%s>%s</option>',
				esc_attr( $role_slug ), $selected, htmlentities( $role['name'] )
			);
		}
		echo '</select>';
		printf(
			'<p class="description">%s</p>',
			__('This is the default role that users will be assigned to if matching Microsoft Entra ID group to '
			 . 'WordPress roles is enabled, but the signed in user isn\'t a member of any of the '
			 . 'configured Microsoft Entra ID groups.', 'aad-sso-wordpress')
		);
	}

	/**
	 * Renders the `enable_auto_provisioning` checkbox control.
	 */
	public function enable_auto_provisioning_callback() {
		$this->render_checkbox_field(
			'enable_auto_provisioning',
			__( 'Automatically create WordPress users, if needed, for authenticated Microsoft Entra ID users.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the site-wide profile photo synchronization control.
	 */
	public function enable_profile_photo_sync_callback() {
		$this->render_checkbox_field(
			'enable_profile_photo_sync',
			__( 'Automatically import a missing profile photo during Entra sign-in and allow users to refresh it from their profile.', 'aad-sso-wordpress' )
		);
		echo '<p class="description">'
			. esc_html__( 'Turning this off stops all automatic and user-initiated Graph photo synchronization. Existing locally stored photos are not deleted.', 'aad-sso-wordpress' )
			. '</p>';
	}

	/**
	 * Renders the `enable_auto_forward_to_aad` checkbox control.
	 */
	public function enable_auto_forward_to_aad_callback() {
		$this->render_checkbox_field(
			'enable_auto_forward_to_aad',
			__( 'Automatically forward users to the Microsoft Entra ID to sign in, skipping the WordPress login screen.',
				'aad-sso-wordpress')
		);
	}

	/**
	 * Renders the `enable_aad_group_to_wp_role` checkbox control.
	 */
	public function enable_aad_group_to_wp_role_callback() {
		$this->render_checkbox_field(
			'enable_aad_group_to_wp_role',
			__( 'Automatically assign WordPress user roles based on Microsoft Entra ID group membership.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `openid_configuration_endpoint` form control
	 **/
	public function openid_configuration_endpoint_callback() {
		$this->render_text_field( 'openid_configuration_endpoint' );
		printf(
			' <a href="#" onclick="jQuery(\'#openid_configuration_endpoint\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			AADSSO_Settings::get_defaults( 'openid_configuration_endpoint' ),
			__( 'Set default', 'aad-sso-wordpress'),
			__( 'The OpenID Connect configuration endpoint to use. To support Microsoft Accounts and external '
			  . 'users (users invited in from other Microsoft Entra ID directories, known sometimes as "B2B users") you '
			  . 'must use: <code>https://login.microsoftonline.com/{tenant-id}/v2.0/.well-known/openid-configuration</code>, '
			  . 'where <code>{tenant-id}</code> is the tenant ID or a verified domain name of your directory.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `enable_full_logout` checkbox control.
	 */
	public function enable_full_logout_callback() {
		$this->render_checkbox_field(
			'enable_full_logout',
			__( 'Do a full logout of Microsoft Entra ID when logging out of WordPress.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders a simple text field and populates it with the setting value.
	 *
	 * @param string $name The setting name for the text input field.
	 */
	public function render_text_field( $name ) {
		$value = isset( $this->settings[ $name ] ) ? esc_attr( $this->settings[ $name ] ) : '';
		printf(
			'<input class="regular-text" type="text" '
			 . 'name="aadsso_settings[%1$s]" id="%1$s" value="%2$s" />',
			$name, $value
		);
	}

	/**
	 * Renders a simple checkbox field and populates it with the setting value.
	 *
	 * @param string $name The setting name for the checkbox input field.
	 * @param string $label The label to use for the checkbox.
	 */
	public function render_checkbox_field( $name, $label ) {
		printf(
			'<input type="checkbox" name="aadsso_settings[%1$s]" id="%1$s" value="%1$s"%2$s />'
			 . '<label for="%1$s">%3$s</label>',
			$name,
			isset( $this->settings[ $name ] ) && $this->settings[ $name ] ? 'checked' : '',
			$label
		);
	}

	/**
	 * Indicates if user is currently on this settings page.
	 */
	public function is_on_options_page() {
		$screen = get_current_screen();
		return $screen->id === $this->options_page_id;
	}

	/**
	 * Ensures jQuery is loaded
	 */
	public function maybe_include_jquery() {
		if ( $this->is_on_options_page() ) {
			wp_enqueue_script( 'jquery' );
		}
	}
}
